### ISSUE TITLE
Help for UI

### ISSUE THREAD

**Issue by DeveloperWOW64** [onein528/FluentTube#1]
@onein528 I once made a concept for a Fluent YouTube client (now abandoned). If you wanted ideas for UI here is the link:
https://watch.codrex.dev

**Comment by DeveloperWOW64** [comment]
lol very broken

**Comment by DeveloperWOW64** [comment]
@onein528 Is this project now abandoned? It seems so.

**Comment by onein528** [comment]
I wanna develop so much. However I have little time.
